from errors import MyError

class PlayerNotFound(MyError, Exception):
    pass